[window]
opacity=0.98

padding.x=15
padding.y=15
decorations = "full"

[font]

normal.family="BlexMono Nerd Font Mono"
normal.style="Normal"

bold.family="BlexMono Nerd Font Mono"
bold.style="Bold"

italic.family="BlexMono Nerd Font Mono"
italic.style="Italic"

bold_italic.family="BlexMono Nerd Font Mono"
bold_italic.style="Bold Italic"

size = 11

[colors]

transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]

TERM="alacritty"
